@startuml minasegura_context
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include <C4/C4_Context>

LAYOUT_WITH_LEGEND()


title Diagrama del contexto del sistema para el aplicativo MinaSegura

Person(encargado_mina, "Encargado", "Encargado de la mina")
Person(admin, "Administrador", "Administrador del sistema Mina Segura")
System(minasegura, "MinaSegura", "Aplicativo que ayuda a la prevencion de explosiones de gas metano y polvo de carbon")
System_Ext(notification, "Sistema de notificaciones", "Sistema de notificaciones gestionado por AWS")

Rel_D(encargado_mina, minasegura, "Administra la seguridad de la mina usando")
Rel_D(admin, minasegura, "Configura los parametros de las minas y sus zonas a traves de")
Rel_R(minasegura, notification, "Usa")

@enduml
