@startuml minasegura_component
!include <C4/C4_Container>

LAYOUT_WITH_LEGEND()

title Diagrama del contenedor del sistema MinaSegura

Person(encargado_mina, "Encargado", "Encargado de la mina")
Person(admin, "Administrador", "Administrador del sistema Mina Segura")

System_Boundary(c1, "MinaSegura") {
    Container(django_app, "Aplicacion Web MinaSegura", "Python, Django", "Permite al usuario el registro de niveles de polvo de carbon y gas metano, visualizacion de alertas, generacion de reportes y programacion de mantenimiento de equipos")
    Container(medicion_api, "API Medicion", "Python, AWS Lambda", "API que permite el registro de niveles de polvo de carbon y gas metano")
    Container(alerta_api, "API Alerta", "Python, AWS Lambda", "API que permite la gestion de alertas por niveles altos de carbon y gas metano, incluyendo la configuracion de los umbrales de las alertas")
    Container(notificacion_api, "API Notificacion", "Python, AWS Lambda", "API que permite el envio de notificaciones SMS hacia los usuarios encargados de la mina")
}
System_Ext(notification, "Sistema de notificaciones", "Sistema de notificaciones gestionado por AWS")

Rel(encargado_mina, django_app, "Interactua")
Rel(admin, django_app, "Interactua")

Rel(django_app, medicion_api, "Se comunica a traves de", "HTTPS")
Rel(django_app, alerta_api, "Se comunica a traves de", "HTTPS")
Rel(django_app, notificacion_api, "Se comunica a traves de", "HTTPS")

Rel(medicion_api, alerta_api, "Envia eventos usando", "Cola de mensajeria")
Rel(alerta_api, notificacion_api, "Envia eventos usando", "Cola de mensajeria")
Rel(notificacion_api, notification, "Invoca a traves de", "SDK")

@enduml
