@startuml minasegura_context
!include <C4/C4_Context>

LAYOUT_WITH_LEGEND()

title Diagrama del contexto del sistema MinaSegura

Person(encargado_mina, "Encargado", "Encargado de la mina")
Person(admin, "Administrador", "Administrador del sistema Mina Segura")

Enterprise_Boundary(c0, "MinaSegura") {

System(django_app, "Sistema MinaSegura", "Aplicacion web para registro y monitoreo de datos de la mina")
System(medicion_api, "Sistema Medicion", "API para registro de datos de polvo de carbon y gas metano")
System(alerta_api, "Sistema Alerta",  "API para gestion de alertas por niveles altos de gases")
System(notificacion_api, "Sistema Notificacion", "API para envio de notificaciones SMS a encargados")
}
System_Ext(notification, "Sistema de notificaciones", "Servicio externo para manejo de notificaciones")

Rel(encargado_mina, django_app, "Interactua")
Rel(admin, django_app, "Interactua")

Rel(django_app, medicion_api, "Se comunica a traves de", "HTTPS")
Rel(django_app, alerta_api, "Se comunica a traves de", "HTTPS")
Rel(django_app, notificacion_api, "Se comunica a traves de", "HTTPS")

Rel_R(medicion_api, alerta_api, "Envia eventos", "Cola de mensajes")
Rel_R(alerta_api, notificacion_api, "Envia eventos", "Cola de mensajes")
Rel(notificacion_api, notification, "Usa", "SDK")

@enduml
