@startuml hu1_sequence
autonumber

title Diagrama del secuencia de la historia MS001

actor Encargado
participant "MinaSegura web"
participant "Lambda Medicion"
participant "Tabla Medicion"
participant "Cola de mensajes"

Encargado->"MinaSegura web": Ingresa datos a registrar
"MinaSegura web"->"Lambda Medicion": Envia data de medicion a registrar
"Lambda Medicion"->"Tabla Medicion": Guarga registro de la medicion
"Tabla Medicion"->"Lambda Medicion": Confirma guardado
"Lambda Medicion"->"Cola de mensajes": Emite evento de medicion registrada
"Lambda Medicion"->"MinaSegura web": Retorna estado del registro
"MinaSegura web"->Encargado:Informa estaod del registro
@enduml
