@startuml hu1_sequence
autonumber

title Diagrama del secuencia de la historia MS014

actor Encargado
participant "MinaSegura web"
Database "MinaSegura Database"

Encargado->"MinaSegura web": Solicita equipos de la mina con mantenimiento planficado
activate Encargado
activate "MinaSegura web"

"MinaSegura web"->"MinaSegura Database": Consulta equipos de la mina con mantenimiento planficado
activate "MinaSegura Database"

"MinaSegura Database" --> "MinaSegura web": Listados de equipos con mantenimiento planificado
deactivate "MinaSegura Database"

"MinaSegura web" --> Encargado: Visualiza equipos de la mina con manteniemiento planificado
deactivate "MinaSegura web"

deactivate Encargado


@enduml
