@startuml hu1_sequence
autonumber

title Diagrama del secuencia de la historia MS017

actor Administrador
participant "MinaSegura web (Admin)"
Database "MinaSegura Database"

Administrador->"MinaSegura web (Admin)": Consulta las minas del sistema
activate Administrador
activate "MinaSegura web (Admin)"

"MinaSegura web (Admin)"->"MinaSegura Database": Consulta todas las minas del sistema
activate "MinaSegura Database"

"MinaSegura Database" --> "MinaSegura web (Admin)": Listados de minas del sistema
deactivate "MinaSegura Database"

"MinaSegura web (Admin)" --> Administrador: Visualiza las minas del sistema
deactivate "MinaSegura web (Admin)"

Administrador->"MinaSegura web (Admin)": Crea nueva mina
activate "MinaSegura web (Admin)"

"MinaSegura web (Admin)"->"MinaSegura Database": Crea nueva mina
activate "MinaSegura Database"

"MinaSegura Database" --> "MinaSegura web (Admin)": Confirmacion creacion \nde la nueva mina
deactivate "MinaSegura Database"

"MinaSegura web (Admin)" --> Administrador: Mina creada correctamente
deactivate "MinaSegura web (Admin)"



deactivate Administrador


@enduml
