@startuml hu1_sequence
autonumber

title Diagrama del secuencia de la historia MS025

actor Administrador
participant "MinaSegura web"

Administrador->"MinaSegura web": realiza solicitud de cierre de sesion como administrador
activate Administrador
activate "MinaSegura web"

"MinaSegura web"->"MinaSegura web": Cierra sesion del usuario administrador


"MinaSegura web" --> Administrador: Redirige a pagina de inicio de sesion
deactivate "MinaSegura web"

deactivate Administrador


@enduml
